FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

RUN apt-get update && \
    apt-get install cron -y && \
    apt-get clean 

WORKDIR /geoip
COPY geoip .
RUN chmod +x geoip.sh

WORKDIR /app
COPY . .

RUN dotnet restore && \
    chmod +x /app/docker-entrypoint.sh && \
    chmod +x /app/scheduler.sh && \
    echo '0 0 * * SUN /app/scheduler.sh >> /dev/null 2>&1' | crontab - 

CMD ./docker-entrypoint.sh & dotnet watch run --project src/Api
