name: "proj-dev"
services:
  aux:
    build:
      context: ./asp
      dockerfile: Dockerfile.aux
    image: aux
    environment:
      HOST: "${HOST}"
      SECRET_KEY: "${SECRET_KEY}"
      SQL_SERVER_URL: "${SQL_SERVER_URL}"
    networks:
      - net
    depends_on:
      - mssql
      - asp
  asp:
    build:
      context: ./asp
      dockerfile: Dockerfile.dev
      args:
        HOST: "${HOST}"
        SECRET_KEY: "${SECRET_KEY}"
        SQL_SERVER_URL: "${SQL_SERVER_URL}"
        GEO_IP_PATH: "${GEO_IP_PATH}"
    image: asp
    ports:
      - "8000:8000"
    environment:
      HOST: "${HOST}"
      SECRET_KEY: "${SECRET_KEY}"
      SQL_SERVER_URL: "${SQL_SERVER_URL}"
      GEO_IP_PATH: "${GEO_IP_PATH}"
    networks:
      - net
    depends_on:
      - mssql
  mssql:
    build:
      context: ./mssql
      dockerfile: Dockerfile
    image: mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      MSSQL_TLS_ENFORCE: 0
    ports:
      - "1433:1433"
    volumes:
      - storage-mssql:/var/opt/mssql
    networks:
      - net

networks:
  net:
    driver: bridge
volumes:
  storage-mssql:
    driver: local
