name: Testing Production

on:
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
  test-production:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create environment
        run: |
         set -e
         content="
            MSSQL_URL='Server=mssql,1433;Database=finshark;User Id=sa;Password=ch@ng3MeSo0nMan;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;'
            SECRET_KEY='$(tr -dc A-Za-z0-9 </dev/urandom | head -c 128; echo)'
            HOST='http://localhost:5246'
            DEPLOY_URL='http://localhost'
            MSSQL_SA_PASSWORD='ch@ng3MeSo0nMan'
            DOMAIN='localhost'
            EMAIL_SUPPORT='aci@mail.com'
            GEO_IP_ACCOUNT_ID='${{ secrets.GEO_IP_ACCOUNT_ID }}'
            GEO_IP_LICENSE_KEY='${{ secrets.GEO_IP_LICENSE_KEY }}'
          "
          echo "$content" > .env

      - name: Build docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.prod.yml"
      
      - name: Run Database Migrations
        run: |
          set -e
          docker compose -f docker-compose.prod.yml exec -T aux ./.tools/dotnet-ef database update --project src/Repository --startup-project src/Api

     